
-- 메뉴 생성
INSERT INTO MENU_ITEM (MENU_ITEM_ID, NAME, PRICE) VALUES (1, '아메리카노', 3500);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, NAME, PRICE) VALUES (2, '카페라떼',  4000);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, NAME, PRICE) VALUES (3, '카페모카',  4500);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, NAME, PRICE) VALUES (4, '카푸치노',  4600);
INSERT INTO MENU_ITEM (MENU_ITEM_ID, NAME, PRICE) VALUES (5, '바닐라라떼', 5100);

-- 포인트 지갑 생성
INSERT INTO POINT_WALLET (WALLET_ID, BALANCE) VALUES (10, 5000);

-- 계정 생성
INSERT INTO CUSTOMER (USER_ID ,USER_NAME ,WALLET_ID, USER_PASSWORD) VALUES ('jiho', '박지호', 10 , '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4');

INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -6, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -5, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -5, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -5, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -5, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -4, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -3, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 4, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 5, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -2, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 1, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 3, DATEADD(DAY, -1, NOW()));
INSERT INTO ORDERS (CUSTOMER_ID, MENU_ITEM_ID, ORDER_DATE_TIME) VALUES (1, 2, DATEADD(DAY, -1, NOW()));
